# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/141sa9YCmlfUggwVXl5cggSerYqSYF5Fw
"""

import random
import pandas as pd
import plotly.express as ps
import plotly.figure_factory as ff
count = []
dice_result = []
for i in range(0,100):
  dice1 = random.randint(1,6)
  dice2 = random.randint(1,6)
  dice_result.append(dice1 + dice2)
  count.append(i)

fig = ps.bar(x=dice_result, y=count)
fig.show()
fig=ff.create_distplot([dice_result],["Result"])
fig.show()

import pandas as pd
import plotly.express as ps
import csv
import plotly.figure_factory as ff

df = pd.read_csv("data.csv")
fig=ff.create_distplot([df["Height(Inches)"].tolist()],["Height"],show_hist=False)
fig.show()
fig=ff.create_distplot([df["Weight(Pounds)"].tolist()],["Weight"],show_hist=False)
fig.show()